// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDNS(arg1, arg2) {
  return window['go']['main']['App']['ApplyDNS'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function DownloadAndInstall(arg1) {
  return window['go']['main']['App']['DownloadAndInstall'](arg1);
}

export function GetCurrentDNS() {
  return window['go']['main']['App']['GetCurrentDNS']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetWindowsUser() {
  return window['go']['main']['App']['GetWindowsUser']();
}

export function ResetDNS() {
  return window['go']['main']['App']['ResetDNS']();
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}
