// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyDNS(arg1:string,arg2:string):Promise<string>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function DownloadAndInstall(arg1:string):Promise<string>;

export function GetCurrentDNS():Promise<string>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetWindowsUser():Promise<string>;

export function ResetDNS():Promise<string>;

export function RunCommand(arg1:string):Promise<string>;
